### ISSUE TITLE
3.1.0b on Mac "Touch Your YubiKey Now" doesn't register

### ISSUE THREAD

**Issue by gboudreau** [Yubico/yubioath-desktop#116]
Using a YubiKey 4.
MacBook Pro (Retina, 15-inch, Mid 2015)
Latest Sierra (10.12.2).

3.1.0b doesn't work. It sees the yubikey, lists my credentials from it, but when I click the round arrows button to get a TOTP token for one of them, it asks me to touch my yubikey, but nothing happens when I do. My only option is to Force-Quit the app.

From the command line: `/Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath show 'AWS'` = works fine.

If I start the GUI from the command line: `/Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-gui`, I see the following as soon as I click the "Show" button for a credential (before I even try to touch my YubiKey):

    Traceback (most recent call last):
      File "yubioath/yubicommon/qt/classes.py", line 85, in customEvent
      File "yubioath/yubicommon/qt/worker.py", line 48, in callback
      File "yubioath/yubicommon/qt/worker.py", line 99, in callback
    CardConnectionException: Card not connected

The same using the 3.0.1 .app works fine (but it quite ugly).

Here's other logs I found in Console.app:
https://youtransfer.pommepause.com/bundle/4ed8cd29-bacf-48e4-a39d-30b6c38e117d/

**Comment by wsargent** [comment]
Running into the same issue here.

**Comment by johanandren** [comment]
I also ran into this and now even "add..." fails 

```
Traceback (most recent call last):
  File "yubioath/gui/__main__.py", line 220, in _add_credential
  File "yubioath/gui/controller.py", line 218, in get_capabilities
  File "yubioath/core/standard.py", line 174, in __init__
  File "yubioath/core/standard.py", line 194, in _select
  File "yubioath/core/standard.py", line 180, in _send
  File "yubioath/core/ccid.py", line 49, in send_apdu
  File "site-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
  File "site-packages/smartcard/CardConnection.py", line 146, in transmit
  File "site-packages/smartcard/pcsc/PCSCCardConnection.py", line 198, in doTransmit
CardConnectionException: Card not connected
```

**Comment by dagheyman** [comment]
A new version of Yubico Authenticator (4.0.0) has been released. Could you try if this version still has the issue? https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by johanandren** [comment]
It works, thanks for fixing!
