### ISSUE TITLE
Unable to detect Yubikey NEO on Fedora 26

### ISSUE THREAD

**Issue by zypA13510** [Yubico/yubioath-desktop#192]
# Description
On Fedora 26, my Yubikey NEO can be detected by _yubikey-personalization-gui_, but not in _yubioath-desktop_. Yubico-OTP mode also works just fine. I don't know if this was caused by the outdated _yubioath-desktop_ version, as I cannot find any repo with newer version, or any guide on how to build it myself (running `./build_qrc.py` directly would fail with many errors).
# Steps to reproduce
1. Install _yubioath-desktop_ by running `dnf install yubioath-desktop` in the terminal.
2. Open _Yubico Authenticator_ in graphical interface, insert Yubikey NEO.
3. (expected) Display OTP stored; (result) Nothing changed, as if no Yubikey is plugged in.
# Environment
```
# dnf list installed
yubioath-desktop.noarch                   3.0.1-3.fc26
kernel.x86_64                     4.12.14-300.fc26

# lshw
        *-pci:1
             description: PCI bridge
             product: Advanced Micro Devices, Inc. [AMD]
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 1.3
             bus info: pci@0000:00:01.3
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:29 ioport:e000(size=4096) memory:f7200000-f75fffff
           *-usb
                description: USB controller
                product: Advanced Micro Devices, Inc. [AMD]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 02
                width: 64 bits
                clock: 33MHz
                capabilities: msi pm pciexpress xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:46 memory:f75a0000-f75a7fff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 4.12.14-300.fc26.x86_64 xhci-hcd
                   physical id: 0
                   bus info: usb@1
                   logical name: usb1
                   version: 4.12
                   capabilities: usb-2.00
                   configuration: driver=hub slots=14 speed=480Mbit/s
                 *-usb:0
                      description: Keyboard
                      product: Yubikey NEO OTP+U2F+CCID
                      vendor: Yubico
                      physical id: 3
                      bus info: usb@1:3
                      version: 3.49
                      capabilities: usb-2.00
                      configuration: driver=usbhid maxpower=30mA speed=12Mbit/s
```

**Comment by emlun** [comment]
Thank you for the detailed report! We'll take a look at it.

**Comment by emlun** [comment]
I'm not able to reproduce this in a Fedora 26 VM. Have you tried reinstalling the `yubioath-desktop` package and, if necessary, its dependencies?

**Comment by zypA13510** [comment]
I tried this just now. I erased all dependencies using `dnf history undo`, then installed again. The issue still exists. FYI this is the list of packages installed by `dnf`:
```
Installed:
  yubioath-desktop.noarch 3.0.1-3.fc26                                          
  kde-filesystem.x86_64 4-55.fc26                                               
  libtomcrypt.x86_64 1.17-31.20160123git912eff4.fc26                            
  libtommath.x86_64 1.0-8.fc26                                                  
  libyubikey.x86_64 1.13-3.fc26                                                 
  pcsc-lite.x86_64 1.8.22-1.fc26                                                
  pcsc-lite-ccid.x86_64 1.4.27-1.fc26                                           
  phonon.x86_64 4.9.1-3.fc26                                                    
  phonon-backend-gstreamer.x86_64 2:4.9.0-2.fc26                                
  proj.x86_64 4.9.3-2.fc26                                                      
  pyscard.x86_64 1.9.5-2.fc26                                                   
  python-pyside.x86_64 1.2.2-7.fc26                                             
  python2-click.noarch 6.7-3.fc26                                               
  python2-crypto.x86_64 2.6.1-14.fc26                                           
  pyusb.noarch 1.0.0-4.fc26                                                     
  qt-mobility-common.x86_64 1.2.2-0.26.20140317git169da60c.fc26                 
  qt-mobility-location.x86_64 1.2.2-0.26.20140317git169da60c.fc26               
  qt-mobility-sensors.x86_64 1.2.2-0.26.20140317git169da60c.fc26                
  qtwebkit.x86_64 2.3.4-16.fc26                                                 
  shiboken-libs.x86_64 1.2.4-2.fc26                                             
  ykpers.x86_64 1.18.0-2.fc26
```

Is there any diagnostic command I can run to help pinpoint the issue?

**Comment by emlun** [comment]
Are you running the app from a terminal?

**Comment by zypA13510** [comment]
Hi @emlun ,
At first I started it in GUI (**Activities** menu on the top left -> **Show Applications** button on the left, with an icon of 9 dots) as described in _Steps to reproduce_ section
I tried running `yubioath-gui` in terminal with same result. Running `yubioath` resulted in the following error:
```
Traceback (most recent call last):
  File "/usr/bin/yubioath", line 11, in <module>
    load_entry_point('yubioath-desktop==3.0.1', 'console_scripts', 'yubioath')()
  File "/usr/lib/python2.7/site-packages/yubioath/cli/__main__.py", line 299, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/yubioath/cli/__main__.py", line 85, in cli
    ctx.obj['dev'] = open_scard(reader)
  File "/usr/lib/python2.7/site-packages/yubioath/core/ccid.py", line 61, in open_scard
    for reader in System.readers():
  File "/usr/lib64/python2.7/site-packages/smartcard/System.py", line 42, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/usr/lib64/python2.7/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCReader.py", line 108, in readers
    hcontext = PCSCContext().getContext()
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 53, in __init__
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
```

**Comment by emlun** [comment]
That I was able to reproduce by stopping `pcscd.service` and `pcscd.socket`. Does `systemctl start pcscd.socket` help?

**Comment by zypA13510** [comment]
Yes, I can confirm that it works on both CLI and GUI now.

Do you think this is a configuration problem? I don't think I changed anything apart from installing the package with `dnf`. What should I do now to make it work after restart, `systemctl enable pcscd.socket` I guess?

Also part of the problem, I think yubioath-desktop lacks documentation for installation on Linux other than Ubuntu. A guide to build from source may be useful in some cases, when repository is not available.

**Comment by emlun** [comment]
Ok, good to hear! :) My guess is that `pcscd.socket` either wasn't running or had crashed somehow. Yes, `systemctl enable pcscd.socket` should do the trick. We might need to document this somewhere. We'll also look into generalizing the build instructions.
