### ISSUE TITLE
Does not detect my yubikey

### ISSUE THREAD

**Issue by kroeckx** [Yubico/yubioath-desktop#311]
- Yubico Authenticator version: current git version 2f4b911430047042e42b38b18c9f98392ee6b105
- Operating system and version: Debian testing
- YubiKey model and version: yubikey 4

I build a version from the git version, I have all dependencies required by the debian/control file.

When I try to run it, I get:
```
qrc:/qml/SetPassword.qml:23:5: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/SettingsDialog.qml:20:5: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/AddCredentialSlot.qml:14:5: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/AddCredential.qml:15:5: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 12, in <module>\n    from ykman.descriptor import get_descriptors\n\n  File \"/usr/lib/python3/dist-packages/ykman/descriptor.py\", line 30, in <module>\n    from .util import PID, TRANSPORT, Mode\n\n  File \"/usr/lib/python3/dist-packages/ykman/util.py\", line 36, in <module>\n    from cryptography import x509\n\n  File \"/usr/lib/python3/dist-packages/cryptography/x509/__init__.py\", line 8, in <module>\n    from cryptography.x509.base import (\n\n  File \"/usr/lib/python3/dist-packages/cryptography/x509/base.py\", line 16, in <module>\n    from cryptography.x509.extensions import Extension, ExtensionType\n\n  File \"/usr/lib/python3/dist-packages/cryptography/x509/extensions.py\", line 18, in <module>\n    from cryptography.hazmat.primitives import constant_time, serialization\n\n  File \"/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py\", line 11, in <module>\n    from cryptography.hazmat.bindings._constant_time import lib\n\nImportError: No module named '_cffi_backend'\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 12, in <module>
    from ykman.descriptor import get_descriptors

  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 30, in <module>
    from .util import PID, TRANSPORT, Mode

  File "/usr/lib/python3/dist-packages/ykman/util.py", line 36, in <module>
    from cryptography import x509

  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (

  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType

  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib

ImportError: No module named '_cffi_backend'
)
```

And then every second I get:
```
NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
```

The application also shows me that no key is inserted, while it is, and other things work fine with it.

**Comment by dagheyman** [comment]
Thanks for the report.

Not sure what is going on here. I can build it on a clean Debian buster VM with the dependencies installed from `apt` (and pyotherside installed from source, since the version in apt is at 1.2). My guess would be there is some issue with the `cryptography` [package](https://github.com/pyca/cryptography/issues/3703).

**Comment by kroeckx** [comment]
The only thing I should have installed from unstable is openssl. I
assume you're not using TLS, so I don't see how it would break
anything. I did not install anything from source.

**Comment by dagheyman** [comment]
> The only thing I should have installed from unstable is openssl

Since the problems seem related to the cryptography module, which uses OpenSSL as a backend, I would guess that this is related somehow.

**Comment by kroeckx** [comment]
Downgrading to openssl 1.1.0 does not fix it, as expected.

**Comment by kroeckx** [comment]
It works again.
