### ISSUE TITLE
Can only add one credential with Yubikey 5 

### ISSUE THREAD

**Issue by OlliC** [Yubico/yubioath-desktop#325]
- Yubico Authenticator version: 3.0.1
- Operating system and version: Ubuntu 18.10
- YubiKey model and version: Yubikey 5 NFC (Firmware: 5.1.2)
- Bug description summary: 

After being able to add the first credential to my new Yubikey 5 it wont let me add a second one. 
The same credential could be added with no problems on my other Yubikey 4. So its not an issue with bad secret key or something like that. This is what yubioath-gui prints on terminal: 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/yubioath/gui/__main__.py", line 224, in _add_credential
    require_touch=dialog.require_touch)
  File "/usr/lib/python2.7/dist-packages/yubioath/gui/controller.py", line 382, in add_cred
    super(GuiController, self).add_cred(dev, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/yubioath/core/controller.py", line 157, in add_cred
    dev.put(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/yubioath/core/standard.py", line 327, in put
    self._send(INS_PUT, data)
  File "/usr/lib/python2.7/dist-packages/yubioath/core/standard.py", line 189, in _send
    raise CardError(status)
CardError: Card Error (6a80):
```

The same "Card Error" happens when trying to add the credential with yubioath command line program.

Steps to reproduce
---

1. Insert a Yubikey 5 NFC
2. Add credentials with File -> Add...

Expected result
---

I can add alot of credentials without problems.

Actual results
---

Crashes with "Card Error" on second credentials.

Other info
---

None

**Comment by OlliC** [comment]
Ok i have solved this issue by now. It was just a problem with the old Yubico Authenticator version 3.0.1 which comes by default with current Ubuntu. I installed the Yubico PPA to get version 4.3.5 which solves this issue.
