### ISSUE TITLE
Does not start on OSX 10.9.5

### ISSUE THREAD

**Issue by jasonm** [Yubico/yubioath-desktop#39]
Not sure if this is specific to the OS version or not, but I am testing on 10.9.5.

*EDIT*: Looks like it does work on 10.10.1.

I downloaded and installed `yubioath-desktop-2.1.1-mac.pkg` from https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-2.1.1-mac.pkg .

When I open the app, it immediately closes.  If I run it via terminal, I get the following output:

```
[/Applications/Yubico Authenticator.app/Contents] ./MacOS/yubioath
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/yubioath.gui.main", line 242, in main
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/yubioath.gui.main", line 113, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/yubioath.gui.controller", line 183, in __init__
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.CardMonitoring", line 158, in run
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.CardRequest", line 59, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCCardRequest", line 81, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCContext", line 53, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCContext", line 40, in __init__
EstablishContextException: 'Failure to establish context: Service not available.'

  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/yubioath.gui.ccid", line 135, in observe_reader
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/yubioath.gui.ccid", line 87, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.System", line 41, in readers
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.reader.ReaderFactory", line 58, in readers
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCReader", line 107, in readers
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCContext", line 53, in __init__
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.1.1/build/tmp23K3iS/out00-PYZ.pyz/smartcard.pcsc.PCSCContext", line 40, in __init__
EstablishContextException: 'Failure to establish context: Service not available.'
QThread: Destroyed while thread is still running
```

The only reference I can find to this string online is in https://github.com/Yubico/python-u2flib-host/issues/1

This is with a YubiKey Edge.  The YubiKey Personalization Tool does run.

**Comment by jasonm** [comment]
I tried restarting the machine too, based on the note about restarting after `osx-patch-ccid` in the README, but that doesn't seem to change anything.

**Comment by jasonm** [comment]
Updated to include that this seems limited to OSX 10.9, and that 10.10 works.

**Comment by jasonm** [comment]
Hm, I'm not sure if it's a related issue, but on 10.10 although the app does start up, the UI stays on "Insert a YubiKey..." even when I insert a YubiKey Edge.

**Comment by dainnilsson** [comment]
This is related to the smartcard portion of the application, which seems to sometimes be missing or at least deactivated in OS X (perhaps until a smartcard is inserted?) causing this failure. The YubiKey Edge has no smartcard component to it, so the real bug here is that the application crashes when this is missing, instead of just ignoring it and deactivating it. I've introduced code that fixes this, so the next version will not have this problem.

As for the "Insert a YubiKey..." message, make sure you have at least one of the slots active in the applications settings, or there will be nothing for the application to show.

**Comment by jasonm** [comment]
Thanks @dainnilsson!
