### ISSUE TITLE
No YubiKey detected macOS

### ISSUE THREAD

**Issue by LandonSchropp** [Yubico/yubioath-desktop#410]
- Yubico Authenticator version: 4.3.6
- Operating system and version: macOS 10.14.5 (running on Mid 2012 Retina MacBook Pro)
- YubiKey model and version: YubiKey 5 Nano (Running 5.1.2 Firmware)
- Bug description summary: YubiKey Manager detects my YubiKey without any problems but Yubico Authenticator can't detect it. The YubiKey works fine on my newer 2017 MacBook Pro at work.

Steps to reproduce
---

1. Plug in the YubiKey.
2. Open YubiKey Manager
4. Open Yubico Authenticator

Expected result
---

The YubiKey should be detected by both applications.

Actual results
---

The YubiKey is detected by YubiKey Manager, but not Yubico Authenticator.

Other info
---

As suggested by @dagheyman in #331, I ran the application with logging enabled and this is the output:

```
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 12, in <module>
    from ykman.descriptor import get_descriptors

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/descriptor.py", line 30, in <module>
    from .util import PID, TRANSPORT, Mode, YUBIKEY

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/util.py", line 41, in <module>
    from OpenSSL import crypto

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 195, in <module>
    Binding.init_static_locks()

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 142, in init_static_locks
    __import__("_ssl")

ImportError: dlopen(/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so
  Reason: image not found
)
qml: Function not found: 'yubikey.init_with_logging' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: Error: Cannot assign [undefined] to int undefined
qml: Function not found: 'yubikey.controller.count_devicfish: '/Applications/Yubico\ Authentic…' terminated by signal SIGTERM (Polite quit r
```

I'd really appreciate a fix for this. I purchased two YubiKeys so I could leave one plugged into each laptop and never have to worry about carrying them around. This is preventing me from fully using my YubiKey setup.

**Comment by emlun** [comment]
Hi, it looks like a library is missing. How did you install Yubico Authenticator?

**Comment by LandonSchropp** [comment]
I used the installer from the website.

**Comment by LandonSchropp** [comment]
That's weird. I tried reinstalling the application and everything worked fine. I'm not sure how I got into the bad state previously, but at least I can move forward now. 🤷‍♂️

**Comment by emlun** [comment]
Yeah, hard to say, but I'm glad you got it working! Let us know if you have any more problems.
