### ISSUE TITLE
Does not start in Ubuntu

### ISSUE THREAD

**Issue by dainnilsson** [Yubico/yubioath-desktop#43]
Installing the current version from the PPA results in a build which will not start:
`pkg_resources.DistributionNotFound: PySide`

The reason is that the python-pyside package does not correctly register PySide as installed. A temporary workaround is to modify the file `/usr/lib/python2.7/dist-packages/yubioath_desktop-2.2.1.egg-info/requires.txt` removing the `PySide` line from it.

**Comment by drohm** [comment]
I'm getting the same issue in LinuxMint 17.2 Xfce x64.

**Comment by dainnilsson** [comment]
There's a new build in the PPA which should resolve this issue.

**Comment by kmpm** [comment]
just made a fresh install using the ppa on ubuntu 16.04 and it doesn't work.
```
$ yubioath
Traceback (most recent call last):
  File "/usr/local/bin/yubioath", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySide' distribution was not found and is required by yubioath-desktop
 ```

**Comment by dainnilsson** [comment]
The PPA doesn't install to /usr/local/, so it doesn't look like you're actually running the version from the PPA. Perhaps you have a lingering installation that's interfering?

**Comment by kmpm** [comment]
Probably lingering but after removing averything that I could find that was related and reinstalling from ppa.
```
$ sudo apt-get install yubioath-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpyside1.2 libshiboken1.2v5 libykpers-1-1 libyubikey0 python-crypto python-pyscard python-pyside.qtcore
  python-pyside.qtgui python-pyside.qtnetwork
Suggested packages:
  python-crypto-dbg python-crypto-doc python-wxgtk3.0
The following NEW packages will be installed:
  libpyside1.2 libshiboken1.2v5 libykpers-1-1 libyubikey0 python-crypto python-pyscard python-pyside.qtcore
  python-pyside.qtgui python-pyside.qtnetwork yubioath-desktop
0 upgraded, 10 newly installed, 0 to remove and 74 not upgraded.
Need to get 0 B/3 309 kB of archives.
After this operation, 19,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package libshiboken1.2v5:amd64.
(Reading database ... 180932 files and directories currently installed.)
Preparing to unpack .../libshiboken1.2v5_1.2.2-2build2_amd64.deb ...
Unpacking libshiboken1.2v5:amd64 (1.2.2-2build2) ...
Selecting previously unselected package libpyside1.2:amd64.
Preparing to unpack .../libpyside1.2_1.2.2-2build2_amd64.deb ...
Unpacking libpyside1.2:amd64 (1.2.2-2build2) ...
Selecting previously unselected package libyubikey0.
Preparing to unpack .../libyubikey0_1.13-1_amd64.deb ...
Unpacking libyubikey0 (1.13-1) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../python-crypto_2.6.1-6build1_amd64.deb ...
Unpacking python-crypto (2.6.1-6build1) ...
Selecting previously unselected package python-pyscard.
Preparing to unpack .../python-pyscard_1.9.2-2_amd64.deb ...
Unpacking python-pyscard (1.9.2-2) ...
Selecting previously unselected package python-pyside.qtcore.
Preparing to unpack .../python-pyside.qtcore_1.2.2-2build2_amd64.deb ...
Unpacking python-pyside.qtcore (1.2.2-2build2) ...
Selecting previously unselected package python-pyside.qtgui.
Preparing to unpack .../python-pyside.qtgui_1.2.2-2build2_amd64.deb ...
Unpacking python-pyside.qtgui (1.2.2-2build2) ...
Selecting previously unselected package python-pyside.qtnetwork.
Preparing to unpack .../python-pyside.qtnetwork_1.2.2-2build2_amd64.deb ...
Unpacking python-pyside.qtnetwork (1.2.2-2build2) ...
Selecting previously unselected package libykpers-1-1:amd64.
Preparing to unpack .../libykpers-1-1_1.17.2-1_amd64.deb ...
Unpacking libykpers-1-1:amd64 (1.17.2-1) ...
Selecting previously unselected package yubioath-desktop.
Preparing to unpack .../yubioath-desktop_2.3.0-1_all.deb ...
Unpacking yubioath-desktop (2.3.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160322.1-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu4) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up libshiboken1.2v5:amd64 (1.2.2-2build2) ...
Setting up libpyside1.2:amd64 (1.2.2-2build2) ...
Setting up libyubikey0 (1.13-1) ...
Setting up python-crypto (2.6.1-6build1) ...
Setting up python-pyscard (1.9.2-2) ...
Setting up python-pyside.qtcore (1.2.2-2build2) ...
Setting up python-pyside.qtgui (1.2.2-2build2) ...
Setting up python-pyside.qtnetwork (1.2.2-2build2) ...
Setting up libykpers-1-1:amd64 (1.17.2-1) ...
Setting up yubioath-desktop (2.3.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu2) ...


$ yubioath
Traceback (most recent call last):
  File "/usr/bin/yubioath", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySide' distribution was not found and is required by yubioath-desktop
```

**Comment by kmpm** [comment]
sorry, it just needed even more cleaning... It's not an issue. Forget all about it.
