### ISSUE TITLE
macOS 10.12 can't detect Yubikey 5 NFC

### ISSUE THREAD

**Issue by galinski** [Yubico/yubioath-desktop#464]
- Yubico Authenticator version: 5.0
- Operating system and version: macOS Sierra 10.12
- YubiKey model and version: 5 NFC
- Bug description summary: 
```
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 11, in <module>
    from ykman.descriptor import (

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/descriptor.py", line 30, in <module>
    from .util import PID, TRANSPORT, Mode, YUBIKEY

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/util.py", line 41, in <module>
    from OpenSSL import crypto

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 195, in <module>
    Binding.init_static_locks()

  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 142, in init_static_locks
    __import__("_ssl")

ImportError: dlopen(/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Applications/Yubico Authenticator.app/Contents/MacOS/../Frameworks/libcrypto.1.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Yubico Authenticator.app/Contents/MacOS/../Frameworks/libcrypto.1.1.dylib
)
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```

Steps to reproduce
---

I download executable version form Yubico website. Run it without root privilege.

Expected result
---

Run app and detect my Yubikey.

Other info
---

I did try to run app with root privilege and the result are:
`$ sudo /Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop
Segmentation fault: 11`

Is something releated to macOS 10.12? I see that it isn't supported.

**Comment by dagheyman** [comment]
Thanks for the report. Yes, this is expected for 10.12 unfortunately. Supporting 10.12 requires us to build the app and dependencies with an older version of xcode, which would stop us from supporting things like Dark Mode in Mojave.
