### ISSUE TITLE
PySide 'not found' error when PySide is installed.

### ISSUE THREAD

**Issue by lrvick** [Yubico/yubioath-desktop#47]
See blow:
```
~> yubioath-cli
Traceback (most recent call last):
  File "/usr/bin/yubioath-cli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySide' distribution was not found and is required by yubioath-desktop
```

PySide is installed:
```
~> ls -1 /usr/lib/python2.7/site-packages/PySide/* 

/usr/lib/python2.7/site-packages/PySide/__init__.py
/usr/lib/python2.7/site-packages/PySide/phonon.so
/usr/lib/python2.7/site-packages/PySide/QtCore.so
/usr/lib/python2.7/site-packages/PySide/QtDeclarative.so
/usr/lib/python2.7/site-packages/PySide/QtGui.so
/usr/lib/python2.7/site-packages/PySide/QtHelp.so
/usr/lib/python2.7/site-packages/PySide/QtMultimedia.so
/usr/lib/python2.7/site-packages/PySide/QtNetwork.so
/usr/lib/python2.7/site-packages/PySide/QtOpenGL.so
/usr/lib/python2.7/site-packages/PySide/QtScript.so
/usr/lib/python2.7/site-packages/PySide/QtScriptTools.so
/usr/lib/python2.7/site-packages/PySide/QtSql.so
/usr/lib/python2.7/site-packages/PySide/QtSvg.so
/usr/lib/python2.7/site-packages/PySide/QtTest.so
/usr/lib/python2.7/site-packages/PySide/QtUiTools.so
/usr/lib/python2.7/site-packages/PySide/QtWebKit.so
/usr/lib/python2.7/site-packages/PySide/QtXmlPatterns.so
/usr/lib/python2.7/site-packages/PySide/QtXml.so
/usr/lib/python2.7/site-packages/PySide/_utils.py
```

Installed via the following AUR package. Another user has noted the same issue here as well.

https://aur.archlinux.org/packages/yubico-yubioath-desktop-git/

**Comment by dainnilsson** [comment]
Probably the same issue as #43. Talk to the AUR package maintainer about it.
