### ISSUE TITLE
Handle QR codes with ECI encoding

### ISSUE THREAD

**Issue by vidartf** [Yubico/yubioath-desktop#537]
- Yubico Authenticator version: 5.0.2
- Operating system and version: Windows 10: 
- YubiKey model and version: N/A
- Bug description summary: Handle scaled QR codes

Steps to reproduce
---

Try to decode a QR code with ECI encoding.

Expected result
---

Works

Actual results
---

Fails to decode auth info. By manually debugging, I see that the QR code I have fails here:

[...]\yubioath-desktop\py\qr\qrdecode.py in parse_bits(bits, version)
    253         return bits_to_bytes(bits[:ln*8]), bits[ln*8:]
    254     else:
--> 255         raise ValueError('Unsupported encoding: %d' % enc)
    256
    257

ValueError: Unsupported encoding: 7

**Comment by dagheyman** [comment]
Thanks, looks like a bug/missing functionality in the QR decoder. Can I ask what service this is?

**Comment by vidartf** [comment]
UK Government Gateway (beta). It seems they are using ECI encoding 26 ([utf8](https://strokescribe.com/en/ECI.html)).

**Comment by vidartf** [comment]
Example buffer (note that I'm using Python 3 here):
`q¤·otpauth://totp/Government%20Gateway:<name here>?secret=<secret>&digits=6&issuer=Government%20Gateway&algorithm=SHA1&period=30<tail>`

**Comment by vidartf** [comment]
for ref: `[4 bits, use ECI] [8 bits, ECI 26 = UTF8][4 bits, Byte mode][183 character length]otpauth...`

**Comment by bjoernv** [comment]
The app also fails for Microsoft 365 multifactor authentication setup.

* Yubico Authenticator version: 5.0.2
* Operating system and version: openSUSE Tumbleweed 20200502 (Linux)
* YubiKey model and version: 4

```Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
2020-05-05T12:13:40+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-05-05T12:13:42+0200 ERROR [yubikey.parse_qr:536] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 534, in parse_qr
    CredentialData.from_uri(qrdecode.decode_qr_data(qr))))
  File "/usr/lib/python3.8/site-packages/ykman/oath.py", line 124, in from_uri
    raise ValueError('Invalid URI scheme')
ValueError: Invalid URI scheme
2020-05-05T12:13:44+0200 ERROR [yubikey.parse_qr:536] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 534, in parse_qr
    CredentialData.from_uri(qrdecode.decode_qr_data(qr))))
  File "/usr/lib/python3.8/site-packages/ykman/oath.py", line 124, in from_uri
    raise ValueError('Invalid URI scheme')
ValueError: Invalid URI scheme
```

**Comment by NobleDraconian** [comment]
Is there any update on this? I'm currently unable to use yubico authenticator with some accounts of mine due to this.

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
