### ISSUE TITLE
OS X 10.11.2 + YubiKey 4 Nano => ImportError: No module named usb

### ISSUE THREAD

**Issue by jdnurmi** [Yubico/yubioath-desktop#63]
After downloading the 2.3.0 binary release for a new key, I've found myself unable to use the Yubico Authenticator app - it sits with the UI asking for me to "Insert a YubiKey".

If I open it in a terminal window, I get the following:
Traceback (most recent call last):
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.3.0/build/tmpcuaJIq/out00-PYZ.pyz/yubioath.gui.controller", line 361, in timerEvent
  File "/Users/dain/yubioath-desktop/yubioath-desktop-2.3.0/build/tmpcuaJIq/out00-PYZ.pyz/yubioath.core.utils", line 167, in ccid_supported_but_disabled
ImportError: No module named usb

(I can import usb from a local python, so not sure where it's trying to pull it from though).

The key works fine in google chrome (once I figured out the 'correct' side up) - so I don't believe there's any _real_ issue with the USB/linkage, merely something in the dependency chain mucking up for me.

I've not tried building locally, but will be happy to give that a try if it's likely to help.

Thanks for any help/advice

**Comment by jdnurmi** [comment]
Ah, it appears I needed to enable CCID via the YubiKey NEO manager (which itself threw errors but eventually behaved).

Sorry for the noise!
