### ISSUE TITLE
macOS Big Sur - apps open but is blank

### ISSUE THREAD

**Issue by lh-engineering** [Yubico/yubioath-desktop#690]
- Yubico Authenticator version: 5.0.4
- Operating system and version: macOS 11.1
- YubiKey model and version: all desktop apps
- Bug description summary: 

I can't get any of the apps to show anything besides a blank interface. I think it may have something to do with the metal settings?

Steps to reproduce
---

1. Open any app

Expected result
---

App functions normally

Actual results
---

Blank app

![Screen Shot 2021-01-29 at 3 12 32 PM](https://user-images.githubusercontent.com/49072813/106336750-6f53e780-6244-11eb-91c4-b93d47e403da.png)

Other info
---

I ran the app on the command line with debug output:

```
$ ./yubioath-desktop --log-level DEBUG
qt.qpa.drawing: Display non non-main thread! Deferring to main thread
2021-01-29T15:07:18-0800 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'230102023f0302023f020400973f5b04010405030501020602000007010f0801000a01009000'
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:200] Success!
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040007a0000005272101'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'790305010271089be4ede95e5ac2449000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.open_devices:339] Failed to connect to reader Yubico YubiKey OTP+FIDO+CCID 01
Traceback (most recent call last):
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ykman/driver_ccid.py", line 333, in open_devices
    conn.connect()
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 121, in connect
    raise NoCardException('Unable to connect', hresult=hresult)
smartcard.Exceptions.NoCardException: Unable to connect: No smart card inserted. (0x-7FEFFFF4)
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 0
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:200] Success!
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 1
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:200] Success!
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x1145f9f70>
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x1145f9f70>
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.__del__:273] Destroy <ykman.driver_ccid.CCIDDriver object at 0x1145fe400>
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x1145fe400>
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x1145fe370>
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x1145fe370>
2021-01-29T15:07:18-0800 DEBUG [ykman.descriptor._open_driver:180] Opening driver for transports: TRANSPORT.CCID, serial: 9912155, key_type: None, mode: None
2021-01-29T15:07:18-0800 DEBUG [ykman.descriptor._open_driver:184] Attempt 1 of 10
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'230102023f0302023f020400973f5b04010405030501020602000007010f0801000a01009000'
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:200] Success!
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2021-01-29T15:07:18-0800 DEBUG [ykman.descriptor._open_driver:187] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x1145fe340> serial: 9912155, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'230102023f0302023f020400973f5b04010405030501020602000007010f0801000a01009000'
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:200] Success!
2021-01-29T15:07:18-0800 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040007a0000005272101'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'790305010271089be4ede95e5ac2449000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a400010a7408000000000333e2d6'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'711641646f62652049443a646f75674064646f616e2e696f760506000c43ac7114416d617a6f6e3a646f75674064646f616e2e696f760506000365a4711443617274613a20646f75674064646f616e2e696f760506000aa608711544726f70626f783a646f75674064646f616e2e696f760506000b1334711346657272617269436861743a20446f756732447605060004a6787113477573746f3a646f75674064646f616e2e696f7605060009240471194b69636b737461727465723a646f75674064646f616e2e696f760506000bb474711d4d312046696e616e63653a646f7567646f616e40676d61696c2e636f6d7605060003585f71174d6963726f736f613c'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a5000000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'66743a646f75674064646f616e2e696f760506000ab41471094e504d3a64646f616e760506000bc56c710a5265646469743a445f44760506000517fa9000'
2021-01-29T15:07:18-0800 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x1145fe340>
2021-01-29T15:07:19-0800 DEBUG [ykman.driver_ccid.__del__:273] Destroy <ykman.driver_ccid.CCIDDriver object at 0x1145fe340>
2021-01-29T15:07:19-0800 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x1145fe340>
```

**Comment by fdennis** [comment]
Hi,
Does this always happen? Even after you restart the app a couple of times? What are "the metal settings"?

**Comment by lh-engineering** [comment]
Yes it happens every time. Sublimetext also had this issue for me: https://forum.sublimetext.com/t/sublimetext-3180-turned-into-totally-dark-after-mojave-upgraded-to-10-14-1-beta/39901

**Comment by lh-engineering** [comment]
I did an NVRAM reset which fixed the issue.
