### ISSUE TITLE
EstablishContextException: 'Failure to establish context: Service not available.' + ImportError: No module named usb

### ISSUE THREAD

**Issue by daurnimator** [Yubico/yubioath-desktop#78]
```
$ yubioath
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/smartcard/CardMonitoring.py", line 158, in run
    self.cardrequest = CardRequest(timeout=0.1)
  File "/usr/lib/python2.7/site-packages/smartcard/CardRequest.py", line 59, in __init__
    cardType, cardServiceClass, timeout)
  File "/usr/lib/python2.7/site-packages/smartcard/pcsc/PCSCCardRequest.py", line 81, in __init__
    self.hcontext = PCSCContext().getContext()
  File "/usr/lib/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 53, in __init__
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/usr/lib/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
EstablishContextException: 'Failure to establish context: Service not available.'

Killing 16887
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yubioath/gui/controller.py", line 361, in timerEvent
    if ccid_supported_but_disabled():
  File "/usr/lib/python2.7/site-packages/yubioath/core/utils.py", line 167, in ccid_supported_but_disabled
    import usb
ImportError: No module named usb
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yubioath/gui/controller.py", line 361, in timerEvent
    if ccid_supported_but_disabled():
  File "/usr/lib/python2.7/site-packages/yubioath/core/utils.py", line 167, in ccid_supported_but_disabled
    import usb
ImportError: No module named usb
```

I saw #63, but my yubikey *is* in CCID mode.

**Comment by daurnimator** [comment]
Hmm, looks like the problem was that pcscd was not running.

**Comment by dagheyman** [comment]
What OS are you running? I'm not able to reproduce this error even when stopping `pcscd`.

**Comment by daurnimator** [comment]
I'm on arch linux.

**Comment by dagheyman** [comment]
It looks like this specific error is no longer possible since f82d198118fbd2a5367642bb2fb50a6ab6e349dd
`Made CCID disabled detection not rely on pyusb.`

**Comment by robkorv** [comment]
I had this on Ubuntu 14.04 and fixed it with `sudo apt-get install python-usb`.

**Comment by daurnimator** [comment]
> I had this on Ubuntu 14.04 and fixed it with sudo apt-get install python-usb

I found other people reporting that but it didn't help me.

**Comment by robkorv** [comment]
@daurnimator I eventually did a fresh install of Ubuntu 16.04 desktop. Now everything works out of the box with the [ppa](https://launchpad.net/~yubico/+archive/ubuntu/stable)

**Comment by bramswenson** [comment]
Same issue here on Arch. I have not installed pcscd or any other supplementary package. After installing acsccid and ensuring it starts at boot with systemd.

```
yaourt -S aur/acsccid
sudo systemctl enable pcscd.service && sudo systemctl start pcscd.service && sudo systemctl status pcscd.service
```

**Comment by robkorv** [comment]
@daurnimator I got it also working on ubuntu 14.04 LTS. See https://github.com/Yubico/yubioath-desktop/issues/86#issuecomment-232656661

**Comment by ElijahLynn** [comment]
> sudo systemctl start pcscd.service

Thanks, this still is an issue as of today and your solution still works. I opened an upstream bug report on the `yubikey-manager` community package here > https://bugs.archlinux.org/task/66671.

**Comment by m4rkv5** [comment]
> yaourt -S aur/acsccid
> sudo systemctl enable pcscd.service
> sudo systemctl start pcscd.service 
> sudo systemctl status pcscd.service
Needed this fix also in 2021 to get my yubikey detected 
OS: Arch Linux x86_64
Kernel: 5.10.16-arch1-1
