### ISSUE TITLE
Stuck in "Insert your YubiKey" on Ubuntu 20.04

### ISSUE THREAD

**Issue by ahemwe** [Yubico/yubioath-desktop#787]
- Yubico Authenticator version: 5.1.0
- Operating system and version: Ubuntu 20.04
- YubiKey model and version: Yubikey 4 (4.3.7)
- Bug description summary: I'm using the key to store OTP-Credentials and read them by yubioath-desktop. This works well on Windows, but not on Ubuntu.

Steps to reproduce
---
Install `yubioath-desktop` via snap.
Insert YubiKey as USB device
Check `lsusb` which returns
`Bus 002 Device 004: ID 1050:0401 Yubico.com Yubikey 4 OTP
`
Open `yubioath-desktop`

Expected result
---
The application should ask me to insert the password for to get access to TOTPs.

Actual results
---
I only see "Insert your YubiKey"

Other info
---
I've started the application in debug mode. This shows cyclic error-messages:

```
ubioath-desktop --log-level DEBUG

(yubioath-desktop:3728): Gtk-WARNING **: 20:57:04.954: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(yubioath-desktop:3728): Gtk-WARNING **: 20:57:04.960: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(yubioath-desktop:3728): Gtk-WARNING **: 20:57:04.962: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
Qt: Session management error: Could not open network socket
/usr/share/libdrm/amdgpu.ids: No such file or directory
2022-03-12T20:57:05+0100 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2022-03-12T20:57:05+0100 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.7
2022-03-12T20:57:05+0100 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.8.7 (default, Oct  5 2021, 13:04:03) 
[GCC 7.5.0]
2022-03-12T20:57:05+0100 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: linux
2022-03-12T20:57:05+0100 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: x86_64
2022-03-12T20:57:05+0100 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: False
WARNING: PC/SC not available. Smart card protocols will not function.
2022-03-12T20:57:05+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:05+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:05+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:05+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:05+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:05+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:06+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:06+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:06+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:07+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:07+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:07+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:08+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:08+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:08+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:09+0100 ERROR [ykman.device.scan_devices:141] Unable to list devices for connection
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 139, in scan_devices
    devs = list_devs()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 85, in inner
    return f()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/device.py", line 102, in list_ccid_devices
    return _list_ccid_devices()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 164, in list_devices
    for reader in list_readers():
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 152, in list_readers
    return System.readers()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
2022-03-12T20:57:09+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/snap/yubioath-desktop/13/usr/lib/python3.8/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 1] Operation not permitted: '/dev/hidraw0'
2022-03-12T20:57:09+0100 DEBUG [fido2.hid.linux.list_descriptors:76] Skip device: [Errno 1] Operation not permitted: '/dev/hidraw0'
```

**Comment by ahemwe** [comment]
After switching on CCID on Windows, the Key works well in Ubuntu. Closing this issue.
