### ISSUE TITLE
Yubico authenticator show no accounts on windows

### ISSUE THREAD

**Issue by Acceyuriko** [Yubico/yubioath-desktop#801]
- Yubico Authenticator version:  5.1.0b
- Operating system and version: 版本	Windows 11 21H2
- YubiKey model and version:  YubiKey 5C FIPS
- Bug description summary: 

Yubico authenticator show no accounts on windows, but it is normal on macos.

Steps to reproduce
---
The yubikey's interface is typec, and my windows only has usb interface, so I bought a typec-to-usb adapter and plugged the yubikey into windows through the adapter. Then, yubico authenticator shows no accounts on windows.
In order to make sure that it is not the problem of the adapter, I plugged the yubikey into the adapter, and then plugged it into the usb interface of the macos docking station, and the yubico authenticator can also be used normally on macos.

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Expected result
---

show my accounts on windows as on macos.

[What did you expect to happen when you did the above?]

Actual results
---
show no accounts.
[What actually happened?]

Other info
---
debug info on windows 
```
2022-06-28T21:31:32+0800 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2022-06-28T21:31:32+0800 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.7
2022-06-28T21:31:32+0800 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
2022-06-28T21:31:32+0800 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: win32
2022-06-28T21:31:33+0800 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: AMD64
2022-06-28T21:31:33+0800 DEBUG [ykman.logging_setup.log_sys_info:52] Windows version: (10, 0, 22000)
2022-06-28T21:31:33+0800 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: True
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.windows.list_descriptors:366] Found CTAP device: b'\\\\?\\hid#vid_1050&pid_0407&mi_01#7&2db310a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
2022-06-28T21:31:33+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:33+0800 DEBUG [yubikit.core.otp.send_and_receive:164] RECV: 260102023f0302023b020400f0f43b04010305030502070602000007010f0801000a01000f0100a80800
2022-06-28T21:31:33+0800 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=15791163, version=Version(major=5, minor=2, patch=7), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False, is_sky=False)
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.windows.list_descriptors:366] Found CTAP device: b'\\\\?\\hid#vid_1050&pid_0407&mi_01#7&2db310a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.windows.list_descriptors:366] Found CTAP device: b'\\\\?\\hid#vid_1050&pid_0407&mi_01#7&2db310a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.call:166] SEND: ffffffff8600084b41af1fbd912c53
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.call:186] RECV: ffffffff8600114b41af1fbd912c53001a0005020502070500000000000000000000000000000000000000000000000000000000000000000000000000000000
2022-06-28T21:31:33+0800 DEBUG [fido2.hid.call:166] SEND: 001a0005c20000
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:186] RECV: 001a0005c20027260102023f0302023b020400f0f43b04010305030502070602000007010f0801000a01000f0100000000000000000000000000000000000000
2022-06-28T21:31:36+0800 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=15791163, version=Version(major=5, minor=2, patch=7), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False, is_sky=False)
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:166] SEND: 001a000590000104
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:186] RECV: 001a00059000bf00aa0183665532465f5632684649444f5f325f306c4649444f5f325f315f50524502826b6372656450726f746563746b686d61632d73656372
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:186] RECV: 001a00050065740350ee882879721c491397753dfcce97072a04a562726bf5627570f564706c6174f469636c69656e7450696ef47563726564656e7469616c4d
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:186] RECV: 001a000501676d7450726576696577f5051904b006810107080818800981637573620a82a263616c672664747970656a7075626c69632d6b6579a263616c6727
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.call:186] RECV: 001a00050264747970656a7075626c69632d6b657900000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2022-06-28T21:31:36+0800 ERROR [yubikey.wrapped:141] Uncaught exception
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 129, in wrapped
    return f(*args, **kwargs)
  File "qrc:///py/yubikey.py", line 785, in ccid_calculate_all
    with self._open_oath() as oath_controller:
  File "qrc:///py/yubikey.py", line 206, in _open_oath
    return connect_to_device(self._current_serial, [SmartCardConnection])[0]
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\device.py", line 228, in connect_to_device
    raise ConnectionNotAvailableException(connection_types)
ykman.device.ConnectionNotAvailableException: No eligiable connections are available ([<class 'yubikit.core.smartcard.SmartCardConnection'>]).
2022-06-28T21:31:36+0800 DEBUG [fido2.hid.windows.list_descriptors:366] Found CTAP device: b'\\\\?\\hid#vid_1050&pid_0407&mi_01#7&2db310a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
2022-06-28T21:31:36+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:36+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:37+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:37+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:38+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
2022-06-28T21:31:38+0800 DEBUG [yubikit.core.otp.send_and_receive:160] SEND: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000136b5b000000
```

debug info on macos
```
2022-06-28T21:35:55+0800 INFO [ykman.logging_setup.setup:76] Initialized logging for level: DEBUG
2022-06-28T21:35:55+0800 INFO [ykman.logging_setup.setup:77] Running ykman version: 4.0.7
2022-06-28T21:35:55+0800 DEBUG [ykman.logging_setup.log_sys_info:48] Python: 3.9.2 (default, Sep 20 2021, 13:20:21) 
[Clang 12.0.0 (clang-1200.0.32.29)]
2022-06-28T21:35:55+0800 DEBUG [ykman.logging_setup.log_sys_info:49] Platform: darwin
2022-06-28T21:35:55+0800 DEBUG [ykman.logging_setup.log_sys_info:50] Arch: x86_64
2022-06-28T21:35:55+0800 DEBUG [ykman.logging_setup.log_sys_info:56] Running as admin: False
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.macos.list_descriptors:414] Found CTAP device: 4294974994
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a4040008a000000527471117
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 5669727475616c206d6772202d2046572076657273696f6e20352e322e37 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 001d000000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 260102023f0302023b020400f0f43b04010305030502070602000007010f0801000a01000f0100 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=15791163, version=Version(major=5, minor=2, patch=7), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False, is_sky=False)
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.macos.list_descriptors:414] Found CTAP device: 4294974994
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.macos.list_descriptors:414] Found CTAP device: 4294974994
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:156] SEND: ffffffff86000882662fb90a7c80ad
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: ffffffff86001182662fb90a7c80ad001b0002020502070500000000000000000000000000000000000000000000000000000000000000000000000000000000
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:156] SEND: 001b0002c20000
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: 001b0002c20027260102023f0302023b020400f0f43b04010305030502070602000007010f0801000a01000f0100000000000000000000000000000000000000
2022-06-28T21:35:55+0800 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=15791163, version=Version(major=5, minor=2, patch=7), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False, is_sky=False)
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:156] SEND: 001b000290000104
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: 001b00029000bf00aa0183665532465f5632684649444f5f325f306c4649444f5f325f315f50524502826b6372656450726f746563746b686d61632d73656372
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: 001b00020065740350ee882879721c491397753dfcce97072a04a562726bf5627570f564706c6174f469636c69656e7450696ef47563726564656e7469616c4d
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: 001b000201676d7450726576696577f5051904b006810107080818800981637573620a82a263616c672664747970656a7075626c69632d6b6579a263616c6727
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.call:176] RECV: 001b00020264747970656a7075626c69632d6b657900000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a4040008a000000527471117
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 5669727475616c206d6772202d2046572076657273696f6e20352e322e37 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 001d000000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 260102023f0302023b020400f0f43b04010305030502070602000007010f0801000a01000f0100 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.device.read_info:453] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=15791163, version=Version(major=5, minor=2, patch=7), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|4|U2F|OTP: 575>}, is_locked=False, is_fips=False, is_sky=False)
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a4040007a0000005272101
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 79030502077108342c5389d2e5d3197408d5529fc8e92a29d27b0101 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a30000207514a60fb04dfd1a7080a2353ee1ae940b7430490826740809429590c3e909af
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 751426ce1299b8409aaf94416aa83513ac241626e5a9 SW=9000
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:118] SEND: 00a400010a740800000000034a801f
2022-06-28T21:35:55+0800 DEBUG [ykman.pcsc.send_and_receive:120] RECV: 71114f70656e56504e3a6c69756a756e68616f7c0106 SW=9000
2022-06-28T21:35:55+0800 DEBUG [fido2.hid.macos.list_descriptors:414] Found CTAP device: 4294974994
2022-06-28T21:35:56+0800 DEBUG [fido2.hid.macos.list_descriptors:414] Found CTAP device: 4294974994
```
[Anything else you would like to add?]

**Comment by Acceyuriko** [comment]
I found out that because I use rdp, so the yubikey should be plugged on the client instead of the server.

see [smart card and remote desktop services](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-and-remote-desktop-services)
